# fly.toml app configuration file generated for bloom-mindmaps on 2026-01-09T22:51:30-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bloom-mindmaps'
primary_region = 'lhr'

[build]
  [build.args]
    NEXT_PUBLIC_SUPABASE_URL = "https://bkjahsglsmvxaxtnxkxo.supabase.co"
    NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJramFoc2dsc212eGF4dG54a3hvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU0NzA3ODEsImV4cCI6MjA4MTA0Njc4MX0.JxfQC0bLfKFPpDuoJqSIcKO7NIzwo6ehAc48dU_Qgsg"
    NEXT_PUBLIC_BACKEND_URL = "https://bloom-api.fly.dev"

[env]
  NODE_ENV = 'production'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
